# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomreservation',
            name='is_allowed',
        ),
        migrations.AddField(
            model_name='roomreservation',
            name='answer',
            field=models.IntegerField(choices=[(0, 'Deny'), (1, 'Allow'), (2, 'Pending')], default=2),
        ),
    ]
