# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20170127_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomreservation',
            old_name='user',
            new_name='creator',
        ),
    ]
