# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20170127_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='employment_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_dismissed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='skype',
        ),
        migrations.RemoveField(
            model_name='user',
            name='specialization',
        ),
    ]
