# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 13:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reservation.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_auto_20170127_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='end_date',
            field=models.DateTimeField(validators=(reservation.validators.validate_working_hours, reservation.validators.validate_not_in_past, reservation.validators.validate_not_late)),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='start_date',
            field=models.DateTimeField(validators=(reservation.validators.validate_working_hours, reservation.validators.validate_not_in_past, reservation.validators.validate_not_late)),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
